InsuranceSurvey/Controllers/TraineeController.cs
using BusinessLayer;
using BusinessLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsuranceSurvey.Controllers
{
    public class TraineeController : Controller
    {
        //
        // GET: /Trainee/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendRequestToSurvery()
        {
            return View();
        }

        public ActionResult TranieeAssignedTask()
        {
            CSGenrateClaim objProperty = new CSGenrateClaim();
            try
            {
                ViewBag.ClaimDetails = BLAssignedClaims.BindTraineeAssignedTask(Convert.ToString(Session["InsuranceUserId"])); //BLGenrateClaim.ViewMyClaims(objProperty);
            }
            catch (Exception ex)
            {
                TempData["errMsg"] = "Error : " + ex.Message;
            }
            
            return View();
        }

        /*=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~*/
    }
}

InsuranceSurvey/Views/Trainee/Index.cshtml
@model BusinessLayer.Models.CSTraineeSurveyorRegistration

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/TraineeMaster.cshtml";
}
@using (Html.BeginForm("Index", "Trainee", FormMethod.Post, new { enctype = "multipart/form-data", @id = "form1" }))
{    
    @Html.HiddenFor(a => a.FkClaimId, new { @id = "hdFkSurveyor" })
    @Html.HiddenFor(a => a.EmailId)
    
    <div class="form_label">
        <div class="col-1"></div>
        <div class="col-3">
            <span>Enter surveyor email id<label class="mandatory">*</label></span>
        </div>
        <div class="col-6">
            <input type="text" id="txtSearchSurvery" class="validate[required,'Please surveyor email id'] Txtbox" maxlength="50" />
        </div>
        <div class="col-2">
            <input type="button" id="btnSearchArroveSurvery" class="Btn" value="Search Survery" />
        </div>
    </div>
    
    <div class="grid_body">
        <table class="mygrid" id="tblDetails">
            <thead>
                <tr>
                    <th>Surveyor Name</th>
                    <th>Surveyor Mobile</th>
                    <th>Surveyor Address</th>
                    <th>Pin</th>
                </tr>
            </thead>
        </table>
    </div>
    
    <div class="form_label dispalyNone">
        <div class="col-12 t_center">
            <input type="button" id="btnSendRequestToSurvery" class="Btn" value="Send Request" />
        </div>
    </div>
}

InsuranceSurvey/Views/Trainee/TranieeAssignedTask.cshtml
@model BusinessLayer.Models.CSGenrateClaim

@{
    ViewBag.Title = "TranieeAssignedTask";
    Layout = "~/Views/Shared/TraineeMaster.cshtml";
}



<script type="text/javascript">
    $(window).load(function () {
        $(".mandatory").html("");
        $("heading").html("View Claim");
    });
</script>

<div>
    @Html.Partial("~/Views/Shared/_assignedtask.cshtml", @Model) 
</div>


<div>
    <form action="/Survery/MarineJIR" enctype="multipart/form-data" id="form1" method="post">
        <input type="hidden" id="fkClaimId" name="fkClaimId" />
        <input type="hidden" id="CheckOpenTable" name="CheckOpenTable" />
        <input type="hidden" id="task" name="task" />
        <input type="hidden" id="Fk_InsdID" name="Fk_InsdID" />
        <input type="hidden" id="Insd_Type" name="InsdType" />
        <input type="hidden" id="InsdName" name="InsdName" />
        <input type="hidden" id="InsdAddress" name="InsdAddress" />
    </form>
</div>

<div>
    <form action="/Survery/lorwork" enctype="multipart/form-data" id="form2" method="post">
        <input type="hidden" id="fklorClaimId" name="fkClaimId" />
        <input type="hidden" id="Task" name="Task" />
        <input type="hidden" id="FkInsdID" name="FkInsdID" />
        <input type="hidden" id="LORInsdType" name="LORInsdType" />
    </form>
</div>

<div>
    <form action="/Survery/ClaimForm" enctype="multipart/form-data" id="form3" method="post">
        <input type="hidden" id="fkClaimIdFrom" name="fkClaimId" />
        <input type="hidden" id="ClaimFormTask" name="task" />
    </form>
</div>

<div>
    <form action="/Survery/SurveyVisits" enctype="multipart/form-data" id="form4" method="post">
        <input type="hidden" id="fkSurveyVisitsClaimId" name="fkClaimId" />
        <input type="hidden" id="SurveyVisitsTask" name="task" />
    </form>
</div>

<div>
    <form action="/Survery/MarineAssessmentDetails" enctype="multipart/form-data" id="form5" method="post">
        <input type="hidden" id="fkAssesmentClaimId" name="fkClaimId" />
        <input type="hidden" id="AssessmentTask" name="task" />
        <input type="hidden" id="MarineTranshipmentAssessmentType" name="AssessmentType" />
    </form>
</div>