InsuranceSurvey/Controllers/MISCFSRController.cs
using BusinessLayer;
using BusinessLayer.BL;
using BusinessLayer.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsuranceSurvey.Controllers
{
    public class MISCFSRController : Controller
    {

        //static int id;
        BLMISCFSR _fsr = new BLMISCFSR();

        //
        // GET: /MISCFSR/

        public ActionResult IntroClaim(string cid, string tableName)
        {
            if (string.IsNullOrEmpty(cid) && (string.IsNullOrEmpty(tableName)))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }

        public ActionResult InsuranceParticulars(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult InsuredClaim(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AssessmentofLoss(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AssessmentofLoss_PartSecond(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult SurveyParticulars(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult SurveyVisit(string cid, string fromTable)
        {

            if (string.IsNullOrEmpty(cid) || string.IsNullOrEmpty(fromTable))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult ObservationsCircumstances(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AboutInsured(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }
        public ActionResult AboutCauseOfLoss(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }

        public ActionResult OtherReportsForMaterialFacts(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }

        }
        public ActionResult LiabilityUnderPolicy(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }

        }
        public ActionResult NatureExtentDamage(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }

        public ActionResult RecoverySubrogation(string cid)
        {
            if (string.IsNullOrEmpty(cid))
            {
                return RedirectToAction("ManageClaims", "Survery");
            }
            else
            {
                return View();
            }
        }


        //public ActionResult saveOtherReportsForMaterialFacts(HttpPostedFileBase PoliceReportPhoto, HttpPostedFileBase FireBrigadeReportPhoto, HttpPostedFileBase MeteorologicalReportPhoto, string Conclusion, int claimId)
        //{

        //    CSMISCOtherReportsForMaterialFacts ormf = new CSMISCOtherReportsForMaterialFacts();
        //    //ormf.Conclusion = Conclusion;
        //    ormf.UserID = Convert.ToInt32(Session["InsuranceUserId"]);
        //    ormf.ClaimID = claimId;
        //    //ormf.PK_MISCORMFID = id;
        //    string fileName = " ";
        //    string Imgpath = " ";
        //    if (PoliceReportPhoto != null)
        //    {
        //        string tempPath = Path.Combine(Server.MapPath("~/files/MISC/"), TempData["tempPolice"].ToString());
        //        if (System.IO.File.Exists(tempPath))
        //        {
        //            System.IO.File.Delete(tempPath);
        //        }

        //        fileName = Guid.NewGuid().ToString() + Path.GetExtension(PoliceReportPhoto.FileName);
        //        ormf.PoliceReportPhoto = fileName;
        //        Imgpath = Path.Combine(Server.MapPath("~/files/MISC/"), fileName);
        //        PoliceReportPhoto.SaveAs(Imgpath);
        //    }
        //    if (FireBrigadeReportPhoto != null)
        //    {
        //        string tempPath = Path.Combine(Server.MapPath("~/files/MISC/"), TempData["tempFire"].ToString());
        //        if (System.IO.File.Exists(tempPath))
        //        {
        //            System.IO.File.Delete(tempPath);
        //        }

        //        fileName = Guid.NewGuid().ToString() + Path.GetExtension(FireBrigadeReportPhoto.FileName);
        //        ormf.FireBrigadeReportPhoto = fileName;
        //        Imgpath = Path.Combine(Server.MapPath("~/files/MISC/"), fileName);
        //        FireBrigadeReportPhoto.SaveAs(Imgpath);
        //    }
        //    if (MeteorologicalReportPhoto != null)
        //    {
        //        string tempPath = Path.Combine(Server.MapPath("~/files/MISC/"), TempData["tempMeteo"].ToString());
        //        if (System.IO.File.Exists(tempPath))
        //        {
        //            System.IO.File.Delete(tempPath);
        //        }

        //        fileName = Guid.NewGuid().ToString() + Path.GetExtension(MeteorologicalReportPhoto.FileName);
        //        ormf.MeteorologicalReportPhoto = fileName;
        //        Imgpath = Path.Combine(Server.MapPath("~/files/MISC/"), fileName);
        //        MeteorologicalReportPhoto.SaveAs(Imgpath);
        //    }
        //    _fsr.saveOtherReportsForMaterialFacts(ormf);
        //    return RedirectToAction("OtherReportsForMaterialFacts", "MISCFSR", new { cid = claimId });
        //    //return View("OtherReportsForMaterialFacts?cid='" + claimId + "'","MISCFSR");

        //}
        #region IntroClaim
        public JsonResult saveIntroClaim(CSMISCFSRIntroClaim ic)
        {
            string Msg = null;
            int Status = 0;
            BLGenrateClaim gc = new BLGenrateClaim();
            try
            {
                ic.UserID = Convert.ToInt32(Session["InsuranceUserId"]);
                gc.updateLocationOfSurvey(Convert.ToInt32(ic.ClaimID), Convert.ToInt32(Session["InsuranceUserId"]), ic.AddressofLossLocation);
                Status = _fsr.saveIntroClaim(ic);
                Msg = Status > 0 ? "Saved Successfully!" : "Failed!Try Again";
            }
            catch (Exception ex)
            {
                Msg = "Error:" + ex.Message;
            }
            return Json(Msg, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getCmtLiabSP()
        {
            string msg = null;
            List<CSMISCCmtLiabSP> listCmtLiabSP = new List<CSMISCCmtLiabSP>();
            try
            {
                listCmtLiabSP = _fsr.getCmtLiabSP();
            }
            catch (Exception ex)
            {
                msg = "Error:" + ex.Message;
            }
            return Json(new { listCmtLiabSP = listCmtLiabSP, msg = msg }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getCL_OP()
        {
            string msg = null;
            List<CSMISCCL_OP> listCL_OP = new List<CSMISCCL_OP>();
            try
            {
                listCL_OP = _fsr.getCL_OP();
            }
            catch (Exception ex)
            {
                msg = "Error:" + ex.Message;
            }
            return Json(new { listCL_OP = listCL_OP, msg = msg }, JsonRequestBehavior.AllowGet);

        }
        public JsonResult getIntroClaim(int claimId)
        {
            string msg = null;
            BLGenrateClaim gc = new BLGenrateClaim();
            CSMISCFSRIntroClaim listIC = new CSMISCFSRIntroClaim();

            try
            {
                int userId = Convert.ToInt32(Session["InsuranceUserId"]);
                listIC = _fsr.getIntroClaim(claimId, userId);
                listIC.AddressofLossLocation = gc.getLocationOfSurvey(claimId, Convert.ToInt32(Session["InsuranceUserId"]));
            }
            catch (Exception ex)
            {
                msg = "Error:" + ex.Message;
            }
            return Json(new { listIC = listIC, msg = msg }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Insurance Particular

InsuranceSurvey/Views/MISCFSR/AboutInsured.cshtml
@{
    ViewBag.Title = "AboutInsured";
    Layout = "~/Views/Shared/SurveryMaster.cshtml";
}


<script>
    $(window).load(function () {
        $("heading").html("ABOUT THE INSURED  ");
    });
</script>

<div ng-controller="AboutInsuredCtrl">

    <form id="formAI">

        <div class="form_label">

            <div class="col-3"><span> NOTE ON BUSINESS PROFILE </span></div>
            <div class="col-12">
                <textarea rows="4" ng-model="ai.NoteBusinessProfile" class="validate[required,'Please enter Date of Intimation of Loss'] Txtbox" id="nbf"></textarea>

            </div>
        </div>
        <div class="form_label">
            <div class="col-12">
                <label><input type="checkbox" ng-model="ai.ChkbxFS" />     Financial Status of last Three years</label>
            </div>
        </div>
        <div ng-show="ai.ChkbxFS==true">
            <div class="form_label">
                <div class="col-12">
                   <span>
                        We have reviewed the Insured's balance sheet of last three years  and tabulated the Insured, sale turn over, gross profit, Net profit and closing stock as on year ending as follows:
                  </span>
                </div>
                <div class="col-12">
                    <textarea rows="2" ng-model="ai.InsuredBalText"></textarea>
                </div>
            </div>
            <div class="form_label">
               
            <div class="col-12">
                <div class="grid_body" style="max-height:400px;">

                    <table class="mygrid">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                                <th colspan="2">Gross Profit </th>
                                <th colspan="2">Net Profit </th>
                                <th></th>
                            </tr>
                            <tr>
                                <th>Financial Year</th>
                                <th>Sales Turnover</th>
                                <th>Rs.</th>
                                <th>%</th>
                                <th>Rs.</th>
                                <th>%</th>
                                <th>Closing Stock</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><select ng-model="fs.FinancialYear"><option>Select</option><option value="2015-2016">2015-2016</option><option value="2016-2017">2016-2017</option><option value="2017-2018">2017-2018</option></select></td>
                                <td><input type="text" ng-model="fs.SalesTurnover" /></td>
                                <td><input type="text" ng-model="fs.GrossProfitRs" valid-number /></td>
                                <td><input type="text" ng-model="fs.GrossProfitPerc" valid-number /></td>
                                <td><input type="text" ng-model="fs.NetProfitRs" valid-number /></td>
                                <td><input type="text" ng-model="fs.NetProfitPerc" valid-number /></td>
                                <td><input type="text" ng-model="fs.ClosingStock" valid-number /></td>
                                <td><input type="hidden" value="First" ng-model="fs.RowName" valid-number /></td>
                            </tr>
                            <tr>
                                <td><select ng-model="sd.FinancialYear"><option>Select</option><option value="2015-2016">2015-2016</option><option value="2016-2017">2016-2017</option><option value="2017-2018">2017-2018</option></select></td>
                                <td><input type="text" ng-model="sd.SalesTurnover" /></td>
                                <td><input type="text" ng-model="sd.GrossProfitRs" valid-number /></td>
                                <td><input type="text" ng-model="sd.GrossProfitPerc" valid-number /></td>
                                <td><input type="text" ng-model="sd.NetProfitRs" valid-number /></td>
                                <td><input type="text" ng-model="sd.NetProfitPerc" valid-number /></td>
                                <td><input type="text" ng-model="sd.ClosingStock" valid-number /></td>
                                <td><input type="hidden" value="Second" ng-model="sd.RowName" valid-number /></td>
                            </tr>
                            <tr>
                                <td><select ng-model="td.FinancialYear"><option>Select</option><option value="2015-2016">2015-2016</option><option value="2016-2017">2016-2017</option><option value="2017-2018">2017-2018</option></select></td>
                                <td><input type="text" ng-model="td.SalesTurnover" /></td>
                                <td><input type="text" ng-model="td.GrossProfitRs" valid-number /></td>
                                <td><input type="text" ng-model="td.GrossProfitPerc" valid-number /></td>
                                <td><input type="text" ng-model="td.NetProfitRs" valid-number /></td>
                                <td><input type="text" ng-model="td.NetProfitPerc" valid-number /></td>
                                <td><input type="text" ng-model="td.ClosingStock" valid-number /></td>
                                <td><input type="hidden" value="Third" ng-model="td.RowName" valid-number /></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>
                </div>
            <div class="form_label">
                <div class="col-12">
                    <span>In view of above year-wise business growth of the Insured business, we may comment that Insured is running a health business, and having good reputation in the market.</span>
                </div>
                <div class="col-12">
                    <textarea rows="2" ng-model="ai.BusinessGrowthText"></textarea>
                </div>
            </div>
        </div>

        <div class="form_label">
            <div class="col-3">
                <span> Descriptions of Site</span>
            </div>
            <div class="col-12">
                <textarea rows="4" ng-model="ai.DescriptionsSite"></textarea>
            </div>
        </div>
        <div class="form_label">
            <div class="col-3">
                <label><input type="checkbox" ng-model="ai.ChkbxLayoutSite" /> Layout of Site, Duly Highlighted affected Area </label>
            </div>
            <div  ng-show="ai.ChkbxLayoutSite==true">
                <div class="col-2">
                <input type="file" id="LayoutSitePhotoDoc"  /></div>
                <div class="col-6">
                <img ng-src="/files/MISC/{{ai.LayoutSitePhotoDoc}}" class="img" style="max-height:40px; max-width:40px; cursor:pointer"/>
               
                <a ng-href="/files/MISC/{{ai.LayoutSitePhotoDoc}}" download >Download</a></div>
            </div>
           
        </div>



        <input type="hidden" value="@Request.QueryString["cid"]" id="cid" />
        <div class="form_label">
            <div class="col-12 t_center mt20">
                <button type="button" class="btn yellow" ng-click="saveAboutInsured()">Submit</button>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <button type="button" id="btnCancel" class="btn yellow" ng-click="cancel()">Cancel</button>
                <button type="button" class="btn yellow" style="float:right;" ng-click="saveAboutInsured('n')">Next</button>
                @*<a href="/MISCFSR/AboutCauseOfLoss?cid=@Request.QueryString["cid"]" class="btn yellow" style="float:right;">
                        Next
                    </a>*@

                <a href="/MISCFSR/ObservationsCircumstances?cid=@Request.QueryString["cid"]" class="btn yellow" style="float:left;">
                    Prev
                </a>
            </div>
        </div>
    </form>
</div>


@section scripts{

    <script src="~/Scripts/Angular/Contoller/MISCFSR/AboutInsured.js"></script>
}

InsuranceSurvey/Views/MISCFSR/OtherReportsForMaterialFacts.cshtml
@{
    ViewBag.Title = "OtherReportsForMaterialFacts";
    Layout = "~/Views/Shared/SurveryMaster.cshtml";
}

<script src="~/Scripts/bootstrap.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script>
    $(window).load(function () {
        $("heading").html("OtherReportsForMaterialFacts");
    });
</script>

<script>
    $(document).on("click", ".img", function () {
        var src = $(this).attr("src");
        var htmlTable = "<div> <img src=" + src + " alt='' style=\"height:180px;width:180px\" /> </div>";
        var div = $("<a href=\"#popup\" id=\"pop\"></a><a href=\"#x\" class=\"overlay\" id=\"popup1\"></a><div class=\"popup\"><div id=\"ViewImg\"></div><a class=\"close\" href=\"#close\"></a></div>");
        $(div).appendTo("body");
        $("#ViewImg").empty();
        $("#ViewImg").append(htmlTable);
        window.location = "#popup1";
    });</script>
<div ng-controller="OtherReportsForMaterialFactsCtrl">
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-sm">

            <!-- Modal content-->
            <div class="modal-content">
                @*<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>*@
                <div class="modal-body" id="modalBody">
                    <div ng-show="ipc==1">

                        @*<button ng-click="show()">Show</button>*@

                        <div class="grid_body table-responsive" style="max-height:400px;">
                            <table class="mygrid">
                                <thead>
                                    <tr>
                                        <th>
                                            IPC Sections
                                        </th>

                                    </tr>
                                </thead>
                                <tbody id="mygridBody">

                                    <tr ng-repeat="ipc in listIPSec">
                                        <td>
                                            <label>
                                                <input type="checkbox" ng-model="ipc.chkboxIPC" />

                                                {{ipc.NameIPCSection}}
                                            </label>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td>
                                            <button type="button" class="btn btn-success" data-dismiss="modal" ng-click="">Submit</button>
                                            @*&nbsp;   &nbsp; &nbsp;
                                            <button type="button" class="btn btn-danger" ng-click="clearCoIns()">
                                                Clear
                                            </button>*@
                                            @*<button ng-click="showIns()">show</button>*@
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>




                    </div>
                </div>
                @*<div class="modal-footer">
                        <button style="float:left;" type="button" class="btn btn-success" data-dismiss="modal">Submit</button >
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>*@
            </div>

        </div>
    </div>
    @using (Html.BeginForm("saveOtherReportsForMaterialFacts", "MISCFSR", FormMethod.Post, new { enctype = "multipart/form-data", @id = "form6" }))
    {
        <h2>Police Report</h2>
        <div class="form_label">

            <div class="col-2">
                <label><input type="checkbox"  ng-model="ormf.C_PR_Tran" />Translation</label>
            </div>
            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Pr_IPC"  />IPC section</label>

            </div>
            <div class="col-2">
                <label><input type="checkbox"  ng-model="ormf.C_Pr_PRC" />Police report content</label>

            </div>
            <div class="col-2">
                <label><input type="checkbox"  ng-model="ormf.C_Pr_Remarks" />Remarks</label>

            </div>
            <div class="col-2">
                @*<input type="file" onchange="angular.element(this).scope().testfunc(event)" />*@
                @*<input type="file" name="PoliceReportPhoto" fileread="ormf.PoliceReportPhoto" />*@
                <input type="file" id="PoliceReportPhoto"  />
            </div>
            <div class="col-2"><img ng-src="/files/MISC/{{ormf.PoliceReportPhoto}}" class="img" style="height:30px; width:30px; cursor:pointer;" />
  <a ng-href="/files/MISC/{{ormf.PoliceReportPhoto}}" download>Download</a>          </div>
        </div>
        <div class="form_label" ng-show="ormf.C_PR_Tran==true">

            <div class="col-2">
                Translation

            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Pr_Tran"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Pr_IPC==true">
            <button type="button" class="btn btn-success" ng-click="showIPC()">
                Sections of Indian Penal Code
            </button>
        </div>
        <div class="form_label" ng-show="ormf.C_Pr_PRC==true">
            <div class="col-2">
                Summary of Police Report content
            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Pr_PRC"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Pr_Remarks==true">
            <div class="col-2">
                Remarks
            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Pr_Remarks"></textarea>
            </div>

        </div>
      
        <h2>Fire Brigade</h2>
        <div class="form_label">

            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Fr_Tran" />Translation</label>
            </div>

            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Fr_sumry" />fire Report Summary</label>

            </div>
            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Fr_Remarks" />Remarks</label>

            </div>
            <div class="col-2">
                <span>Fire Brigade Report</span>
            </div>
            <div class="col-2">
                <input type="file" id="FireBrigadeReportPhoto"/>
            </div>
            <div class="col-2"><img ng-src="/files/MISC/{{ormf.FireBrigadeReportPhoto}}" class="img" style="height:30px; width:30px; cursor:pointer;" /><a ng-href="/files/MISC/{{ormf.FireBrigadeReportPhoto}}" download>Download</a></div>
        </div>
        <div class="form_label" ng-show="ormf.C_Fr_Tran==true">
            <div class="col-2">
                Translation

            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Fr_Tran"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Fr_sumry==true">
            <div class="col-2">
                Fire Brigade Report Summary

            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Fr_Sumry"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Fr_Remarks==true">
            <div class="col-2">
                Remarks
            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Fr_Remarks"></textarea>
            </div>

        </div>
        <h2>Meteorological Report </h2>
        <div class="form_label">

            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Mr_Tran" />Translation</label>
            </div>

            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Mr_Sumry"/>Met Report Summary</label>

            </div>
            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Mr_Remarks" />Remarks</label>

            </div>

            <div class="col-2">
                <span>Meteorological Report </span>
            </div>
            <div class="col-2">
                <input type="file" id="MeteorologicalReportPhoto"  />
            </div>
            <div class="col-2"><img ng-src="/files/MISC/{{ormf.MeteorologicalReportPhoto}}" class="img" style="height:30px; width:30px; cursor:pointer;" /> <a ng-href="/files/MISC/{{ormf.MeteorologicalReportPhoto}}" download>Download</a></div>
        </div>
        <div class="form_label" ng-show="ormf.C_Mr_Tran==true">
            <div class="col-2">
                Translation

            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Mr_Tran"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Mr_Sumry==true">
            <div class="col-2">
                Meteorological Report Summary


            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Mr_Sumry"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Mr_Remarks==true">
            <div class="col-2">
                Remarks
            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Mr_Remarks"></textarea>
            </div>

        </div>
        <h2>
            Forensic Science Lab Report (FSLR)
        </h2>
        <div class="form_label">

            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Fslr_Tran" />Translation</label>
            </div>

            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Fslr_Sumry" />FSLR Summary</label>

            </div>
            <div class="col-2">
                <label><input type="checkbox" ng-model="ormf.C_Fslr_Remarks" />Remarks</label>

            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Fslr_Tran==true">
            <div class="col-2">
                Translation

            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Fslr_Tran"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Fslr_Sumry==true">
            <div class="col-2">
                FSLR Summary


            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Fslr_Sumry"></textarea>
            </div>

        </div>
        <div class="form_label" ng-show="ormf.C_Fslr_Remarks==true">
            <div class="col-2">
                Remarks
            </div>

            <div class="col-10">
                <textarea rows="4" ng-model="ormf.Fslr_Remarks"></textarea>
            </div>

        </div>


        <input type="hidden" value="@Request.QueryString["cid"]" name="claimId" id="cid" />
        <div class="form_label">
            <div class="col-12 t_center mt20">
               @*<button type="submit" class="btn yellow" id="sbt" ng-show="d==0">Submit</button>*@
                <button type="button" class="btn yellow" ng-click="saveOtherReportsForMaterialFacts()">Submit</button>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <button type="button" id="btnCancel" class="btn yellow" ng-click="cancel()">Cancel</button>
                @*<button type="button" class="btn btn-primary" ng-click="photoCheck()">photo</button>*@
                <button type="button" style="float:right;" class="btn yellow" ng-click="saveOtherReportsForMaterialFacts('n')">Next</button>
                <a href="/MISCFSR/AboutCauseOfLoss?cid=@Request.QueryString["cid"]" class="btn yellow" style="float:left;">
                    Prev
                </a>
            </div>
        </div>
    }

</div>
@section scripts{

    <script src="~/Scripts/Angular/Contoller/MISCFSR/OtherReportsForMaterialFactsCtrl.js"></script>
}

InsuranceSurvey/Views/MISCFSR/SurveyVisit.cshtml
@{
    ViewBag.Title = "SurveyVisit";
    Layout = "~/Views/Shared/SurveryMaster.cshtml";
}
<script>
    $(window).load(function () {
        $("heading").html("Detail of Other Survey Visits");
    });
</script>

<div ng-controller="SurveyVisitCtrl">
    <input type="hidden" value="@Request.QueryString["cid"]" id="cid" />
    <input type="hidden" value="@Request.QueryString["fromTable"]" id="fromTable" />
    <div ng-include="'/Templates/Common/AddVisit.html'">
    </div>
</div>
@section scripts{

    <script src="~/Scripts/Angular/Contoller/MISCFSR/SurveyVisitCtrl.js"></script>
}